# Initialize

tap caskroom/homebrew-cask || :
tap homebrew/versions || :
tap homebrew/science || :
tap caskroom/versions || :
tap mrkn/mrkn_casks || :
update || :

# Basic packages

install brew-cask || :
install lv || :
install ag || :
install git || :
install tig || :
install hub || :
install csshx || :
install autossh || :
install tree || :
install tmux || :
install reattach-to-user-namespace || :
install xz || :

cask install keyremap4macbook || :
cask install aquaskk || :
cask install showy-edge || :
cask install alfred || :
cask install bartender || :
cask install iterm2-beta || :
cask install macvim-kaoriya || :
cask install google-chrome-dev || :
cask install istat-menus || :
cask install insomnia-x || :
cask install soundflower || :
cask install dropbox || :
cask install airdisplay || :
cask install gpgtools || :
cask install dterm || :
cask install xquartz || :

# Utilities

install libdvdcss || :
install ffmpeg --with-freetype --with-libass --with-libbluray --with-libcaca --with-libquvi --with-libvidstab --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools --with-x265 || :

cask install cyberduck || :
cask install omnigraffle || :
cask install send-to-kindle || :
cask install flip4mac || :
cask install mactex || :
cask install bathyscaphe || :
cask install vlc || :
cask install calibre || :
cask install anki || :
cask install adobe-reader || :
cask install skype || :
cask install hipchat || :
cask install quartz-clocks || :
cask install licecap || :
cask install flash || :
cask install trailer || :
cask install keyboard-cleaner || :
cask install handbrake || :

# Development packages

install phantomjs || :
install haskell-platform || :
install erlang --devel || :
install elixir || :
install r || :
install postgresql || :
install mysql || :
install redis || :
install mecab || :

cask install firefox || :
cask install java || :
cask install rstudio || :
cask install pharo || :
cask install sequel-pro || :
cask install emacs || :
cask install julia || :
cask install genymotion || :

# VMs

cask install vmware-fusion || :
cask install virtualbox || :
cask install vagrant || :
install docker || :
install boot2docker || :
